int32[] input_sequence
---
int32 total_count
int32 sequence_size
bool success
string error_msg
---
int32 total_count_progress
float32 total_percentage_progress
int32 current_phase
int32 phase_size
int32 phase_count_progress
float32 phase_percentage_progress
